apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarymanagement
  template:
    metadata:
      labels:
        app: librarymanagement
    spec:
      containers:
        - name: librarymanagement
          image: akshatpandya04/librarymanagement:{{IMAGE_TAG}}
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://34.135.101.107:3306/librarydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "test_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Test_db_01"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
          ports:
            - containerPort: 8080
