apiVersion: v1
kind: Service
metadata:
  name: librarymanagement-service
spec:
  type: LoadBalancer
  selector:
    app: librarymanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
