apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarymanagement
  template:
    metadata:
      labels:
        app: librarymanagement
    spec:
      containers:
        - name: librarymanagement
          image: akshatpandya04/librarymanagement:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: librarymanagement-service
spec:
  type: LoadBalancer
  selector:
    app: librarymanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
