apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarymanagement
  template:
    metadata:
      labels:
        app: librarymanagement
    spec:
      containers:
        - name: librarymanagement
          image: akshatpandya04/librarymanagement:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/librarydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "5fdkyi2mas"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
          ports:
            - containerPort: 8080
